import type { Handle } from '@sveltejs/kit';
import { defaultLocale, isLocale, localeCookie } from '$lib/i18n';

// Content-Security-Policy is generated by SvelteKit (see `csp` in vite.config.ts).
const securityHeaders = {
	'Cross-Origin-Opener-Policy': 'same-origin',
	'Permissions-Policy': 'camera=(self), microphone=(), geolocation=()',
	'Referrer-Policy': 'strict-origin-when-cross-origin',
	'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
	'X-Content-Type-Options': 'nosniff'
};

export const handle: Handle = async ({ event, resolve }) => {
	const saved = event.cookies.get(localeCookie);
	event.locals.locale = isLocale(saved) ? saved : defaultLocale;
	const response = await resolve(event, {
		transformPageChunk: ({ html }) => html.replace('%lang%', event.locals.locale)
	});
	response.headers.set('Content-Language', event.locals.locale);
	response.headers.set('Cache-Control', 'private, no-store');
	for (const [name, value] of Object.entries(securityHeaders)) response.headers.set(name, value);
	return response;
};
