import { json, type Handle, type RequestEvent } from '@sveltejs/kit';
import { pathLocale } from '$lib/paths';

// Headers for Worker-rendered responses. Prerendered pages and static assets are served without the
// Worker and get the same list from `_headers`; keep the two in sync. The Content-Security-Policy
// itself is generated by SvelteKit (see `csp` in vite.config.ts).
const securityHeaders = {
	'Cross-Origin-Opener-Policy': 'same-origin',
	'Permissions-Policy': 'camera=(self), microphone=(), geolocation=()',
	'Referrer-Policy': 'strict-origin-when-cross-origin',
	'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
	'X-Content-Type-Options': 'nosniff'
};

export const handle: Handle = async ({ event, resolve }) => {
	// From the path, so a page that doesn't exist is in the language its address asks for.
	const locale = pathLocale(event.url.pathname);
	const app = event.route.id?.startsWith('/(app)') ?? false;
	const response = isCrossSite(event)
		? json({ message: 'cross-site' }, { status: 403 })
		: await runToEnd(
				event,
				resolve(event, {
					transformPageChunk: ({ html }) => html.replace('%lang%', locale),
					// Preload the fonts first paint needs. Only Croatian uses Latin Extended (č ć đ š ž), and app
					// pages open with body text, so they skip the display font.
					preload: ({ type, path }) =>
						type === 'js' ||
						type === 'css' ||
						(type === 'font' &&
							(locale === 'hr' || !path.includes('-latin-ext-')) &&
							!(app && path.includes('hedvig-letters-serif')))
				})
			);
	response.headers.set('Content-Language', locale);
	response.headers.set('Cache-Control', 'private, no-store');
	for (const [name, value] of Object.entries(securityHeaders)) response.headers.set(name, value);
	return response;
};

/** Whether a request may change something: every method but GET and HEAD. */
function changes({ method }: Request) {
	return method !== 'GET' && method !== 'HEAD';
}

// A request that changes something runs to its end even if the device disconnects midway, so a change to R2
// and the database finishes: R2 keeps nothing the database doesn't count, deleted bytes don't stay, and
// notifications go out.
function runToEnd({ request, platform }: RequestEvent, resolving: Response | Promise<Response>) {
	const done = Promise.resolve(resolving);
	if (changes(request)) platform?.ctx.waitUntil(done.catch(() => {}));
	return done;
}

// Requests that change something must come from this installation's own pages. Browsers send Origin with
// them, so a request from another site, or one without Origin, is refused before any route runs. Every
// such request is checked, whatever its path looks like. Session cookies are also SameSite=Strict
// (src/lib/server/session.ts).
function isCrossSite({ request, url }: RequestEvent) {
	return changes(request) && request.headers.get('origin') !== url.origin;
}
